# Site settings
title: Leah Kemple
tagline: 
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "https://leahkemple.com" # the subpath of your site, e.g. /blog
url: "https://leahkemple.com" # the base hostname & protocol for your site

# Plugins
plugins: ["jekyll-paginate-v2"]

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/sass


# # Pagination
# paginate: 4
# paginate_path: "/:category/:num/"
blog_path: "/blog/:num/"
works_path: "/works/:num/"
news_path: "/news/:num/"
# paginate_path2: "/works/page:num/"

# Due to us using the categories for posts then it is advisable to explicitly specify a 
# permalink structure for the site. Otherwise Jekyll attempts to organize the pages in folders
# by the category names and it doesn't understand multi-categories to well :/
permalink: /:categories/:title/
# permalink: pretty

# Pagination Settings
pagination:
  enabled: true
  per_page: 6
  permalink: '/:num/'
  title: 'Page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  debug: false

# Featured post
# The URL of the post that will be featured in the sidebar
# This is accessible as {{ page.id }} and will depend on your
# URL format settings
featured_post: /jekyll/update/2016/10/03/welcome-to-jekyll

# Google Analytics
google_analytics: UA-111177172-3